In [51]:
#Python - Scripting language
#Object oreinted, 3rd party support, Dynamic Typing(Compiler assigns type),Interpreted langauge
# """ cjewbvier2bvp32brv3rb2vwfpibr
# vko3nevn2r3jkbvkj32n
# jb23nvjb3ikv """

In [1]:
i=1234567890 #Unlimited length
print(i)
print("abc")
str="sbc"



1234567890
abc


In [2]:
str

'sbc'

In [4]:
print(0X20)

32


In [6]:
type(0X20)

int

In [7]:
x=2.5
y=45e-1
print(y)

4.5


In [9]:
x=True
x

True

In [10]:
print("ABC")
print("DEF")
print("ABC",end="")
print("DEF")

ABC
DEF
ABCDEF


In [160]:
#Fstrings
x=123
b=True
print(f"Hey why you have {x} chocoloates it that {b}?")

Hey why you have 123 chocoloates it that True?


In [161]:
x = 10
y = 20
print(f"{x = }, {y = }")


x = 10, y = 20


Lists

In [71]:
l=list()

In [72]:
l

[]

In [73]:
l=[]
l

[]

In [74]:
for i in range(10):#Range properties x,y;x;x,y,skip
  l.append(i)

In [75]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [76]:
#Multiple assignment
a=b=c=1
print(a,b,c)

1 1 1


In [77]:
a,b,c=1,2.4,"xy"
print(a,b,c)#Values to unpack - too many/not enough

1 2.4 xy


In [78]:
print("Why is the anseer of this equal to " + "5" + "?")#Adding strings

Why is the anseer of this equal to 5?


In [110]:
l=[i for i in "ABC"]

In [111]:
l

['A', 'B', 'C']

In [112]:
l[:2]

['A', 'B']

In [150]:
a = "Hello World!"
print(a[::-1])

!dlroW olleH


Boolen Conditions

In [159]:
x=True
print( not x)

False


In [81]:
x=True
y=2 if x else 3
print(y)

2


In [82]:
len(l)

3

In [83]:
def list_convert():
    t = (4,3,5,0,1)      # define a tuple
    s = 'hello world!'   # define a string
    d = {'name':"Eyong","age":30,"gender":"Male"}  # define a dict

    # convert all sequences to list
    t_list, s_list, d_list = list(t), list(s), list(d)
    print(list(d.values()))
    # create empty list
    empty_list = list()

    print("tuple_to_list: ", t_list)
    print("string_to_list: ", s_list)
    print("dict_to_list: ", d_list)
    print("empty_list: ", empty_list)
list_convert()

['Eyong', 30, 'Male']
tuple_to_list:  [4, 3, 5, 0, 1]
string_to_list:  ['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd', '!']
dict_to_list:  ['name', 'age', 'gender']
empty_list:  []


In [105]:
names=["abc","def","xy"]
list(enumerate(names,3))

[(3, 'abc'), (4, 'def'), (5, 'xy')]

In [107]:
lx=filter(lambda name: len(name) >=3, names)
list(lx)

['abc', 'def']

In [164]:
a = [1, 1, 2, 3, 4, 5, 5, 5, 6, 7, 2, 2]
print(list(set(a)))

[1, 2, 3, 4, 5, 6, 7]


In [98]:
names1=["pqr","stu","wxyz"]
for x,y in zip(names,names1):
  print(x+" "+y)

abc pqr
def stu
xyz wxyz


In [84]:
l=list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [85]:
sum(l)

45

In [86]:
print(min(l),max(l))

0 9


In [87]:
l.reverse()
l

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [88]:
l.sort()
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [101]:
l.reverse()
l1=sorted(l,key= lambda x:-x)
l1

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [102]:
l1=reversed(l1)
l1=list(l1)
l1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [104]:
l2=list(map(lambda x: x+2,l1))
l2

[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

LOOPS

In [55]:
l=['a','b','c','d']
for i in l :
  print(i)
for i in range(len(l)):
  print(l[i])
i=0
while i< len(l):
  print(l[i])
  i+=1
  #No do while in python- while(True)

a
b
c
d
a
b
c
d
a
b
c
d


Dictionaries

In [113]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

In [115]:
thisdict["brand"]

'Ford'

In [117]:
#Duplicates will overwrite exitsing values

In [118]:
thisdict = dict(name = "John", age = 36, country = "Norway")

In [119]:
thisdict

{'name': 'John', 'age': 36, 'country': 'Norway'}

In [120]:
thisdict.get("name")

'John'

In [121]:
thisdict.items()

dict_items([('name', 'John'), ('age', 36), ('country', 'Norway')])

In [122]:
thisdict.keys()

dict_keys(['name', 'age', 'country'])

In [123]:
thisdict.values()

dict_values(['John', 36, 'Norway'])

In [124]:
thisdict.pop("age")

36

In [125]:
thisdict

{'name': 'John', 'country': 'Norway'}

In [126]:
thisdict.update(b=200, d=400)

In [127]:
thisdict

{'name': 'John', 'country': 'Norway', 'b': 200, 'd': 400}

In [163]:
a = {"a": 1, "b": 2}
b = {"c": 3, "d": 4}

a_and_b = a | b
print(a_and_b)

{'a': 1, 'b': 2, 'c': 3, 'd': 4}


String


In [137]:
str="hello how are you?"

In [138]:
str1=str.capitalize()
str1

'Hello how are you?'

In [139]:
str2=str.upper()
str2

'HELLO HOW ARE YOU?'

In [140]:
str3=str.lower()
str3

'hello how are you?'

In [141]:
str4=str.title()
str4

'Hello How Are You?'

In [144]:
str.find("a")

10

In [145]:
str.isdecimal()

False

In [146]:
str.rfind('h')

6

In [147]:
liststr=str.partition("how")
liststr

('hello ', 'how', ' are you?')

In [148]:
liststr=str.split(" ")
liststr

['hello', 'how', 'are', 'you?']

In [149]:
str.index("y")

14

Tuple

In [135]:
t=tuple()

In [136]:
t

()

In [28]:
t=()

In [29]:
t

()

In [40]:
t=(i for i in "ABC")#Generator object

In [46]:

for i in t:
  print(i)

In [162]:
a = (1, 2, [1, 2, 3])
a[2].append(4)
print(a)

(1, 2, [1, 2, 3, 4])


In [30]:
#t.append(12)

AttributeError: ignored

Some Amazing things

In [155]:
x=1
y* = 1,2,3
print(x, y)

SyntaxError: ignored

In [156]:
a = [x * 2 for x in range(10)]
list(a)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [158]:
a = [1, 2, 3, 4 ,5]
b = a

# Change the 4th index in b
b[4] = 7

print(id(a))
print(id(b))
print(a) # Remember we did not explicitly make changes to a.



131949762539584
131949762539584
[1, 2, 3, 4, 7]


Functions

In [166]:
def func( a , b , c):
  x=100
  return x+(a + b+ c)
print(func(1,2,3))

106


In [169]:
def func(a , *b ) :
  print(b)
  for i in b:
    a+=i
  return a
print(func(1,2,3))

(2, 3)
6


In [177]:
class Person:

    # init method or constructor
    def __init__(self, name):
        self.name = name

    # Sample Method
    def say_hi(self):
        print('Hello, my name is', self.name)


p = Person('Nikhil')
p.say_hi()
print(vars(p))
print(dir(p))
#Explicit is better than implicit
#Public by default

Hello, my name is Nikhil
{'name': 'Nikhil'}
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'name', 'say_hi']


# NUMPY & PANDAS BASICS

In [178]:
import numpy as np
import pandas as pd


In [ ]:
# NumPy is a library for the Python programming language,
#  adding support for large, multi-dimensional arrays and matrices,
#  along with a large collection of high-level mathematical functions to operate on these arrays.

In [ ]:
# pandas is a software library written for the Python programming language for data manipulation and analysis.
# In particular, it offers data structures and operations for manipulating numerical tables and time series.

In [179]:
df=pd.read_csv('/content/Nat_Gas.csv')

In [180]:
df

Dates  Prices
0   10/31/20   10.10
1   11/30/20   10.30
2   12/31/20   11.00
3    1/31/21   10.90
4    2/28/21   10.90
5    3/31/21   10.90
6    4/30/21   10.40
7    5/31/21    9.84
8    6/30/21   10.00
9    7/31/21   10.10
10   8/31/21   10.30
11   9/30/21   10.20
12  10/31/21   10.10
13  11/30/21   11.20
14  12/31/21   11.40
15   1/31/22   11.50
16   2/28/22   11.80
17   3/31/22   11.50
18   4/30/22   10.70
19   5/31/22   10.70
20   6/30/22   10.40
21   7/31/22   10.50
22   8/31/22   10.40
23   9/30/22   10.80
24  10/31/22   11.00
25  11/30/22   11.60
26  12/31/22   11.60
27   1/31/23   12.10
28   2/28/23   11.70
29   3/31/23   12.00
30   4/30/23   11.50
31   5/31/23   11.20
32   6/30/23   10.90
33   7/31/23   11.40
34   8/31/23   11.10
35   9/30/23   11.50
36  10/31/23   11.80
37  11/30/23   12.20
38  12/31/23   12.80
39   1/31/24   12.60
40   2/29/24   12.40
41   3/31/24   12.70
42   4/30/24   12.10
43   5/31/24   11.40
44   6/30/24   11.50
45   7/31/24   11.60
46   8/31/24   11.50
47   9/30/24   11.80

In [183]:
import numpy as np

# Creating a NumPy array from a Python list
python_list = [1, 2, 3, 4, 5]
numpy_array = np.array(python_list)

# Creating a NumPy array with zeros
zeros_array = np.zeros(5)  # Creates an array of zeros with shape (5,)

# Creating a NumPy array with ones
ones_array = np.ones(5)    # Creates an array of ones with shape (5,)

# Creating a NumPy identity matrix
identity_matrix = np.eye(3)  # Creates a 3x3 identity matrix

# Creating a NumPy array with a specified range
range_array = np.arange(0, 10, 2)  # Creates an array from 0 to 8 with step 2

# Creating a NumPy array with random values
random_array = np.random.rand(3, 3)  # Creates a 3x3 array with random values between 0 and 1
print(random_array)
# Creating a NumPy array with a specific data type (e.g., float)
float_array = np.array([1, 2, 3], dtype=float)

# Checking array attributes
print(numpy_array.shape)  # Prints the shape of the array
print(numpy_array.dtype)  # Prints the data type of the array


[[0.79914393 0.40400166 0.89442207]
 [0.4281099  0.1039107  0.85942759]
 [0.34304621 0.77234443 0.04051015]]
(5,)
int64


In [184]:
import numpy as np

# Element-wise operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result_add = arr1 + arr2  # Element-wise addition
result_sub = arr1 - arr2  # Element-wise subtraction
result_mul = arr1 * arr2  # Element-wise multiplication
result_div = arr1 / arr2  # Element-wise division

# Broadcasting - applying operations on arrays with different shapes
arr = np.array([1, 2, 3])
scalar = 2

result_broadcast = arr + scalar  # Broadcasting scalar to the array

# Aggregation functions
arr = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(arr)  # Calculate the mean
sum_value = np.sum(arr)    # Calculate the sum
max_value = np.max(arr)    # Find the maximum value
min_value = np.min(arr)    # Find the minimum value

# Indexing and slicing
arr = np.array([0, 1, 2, 3, 4, 5])
element = arr[2]         # Accessing a specific element (index 2)
slice_result = arr[1:4]  # Slicing to get elements from index 1 to 3

print(result_add, result_sub, result_mul, result_div)
print(result_broadcast)
print(mean_value, sum_value, max_value, min_value)
print(element, slice_result)


[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ]
[3 4 5]
3.0 15 5 1
2 [1 2 3]


In [185]:
import pandas as pd

# Creating a Pandas Series
data = [1, 2, 3, 4, 5]
series = pd.Series(data)

# Creating a Pandas DataFrame from a dictionary
data_dict = {'Name': ['Alice', 'Bob', 'Charlie'],
             'Age': [25, 30, 35]}
df = pd.DataFrame(data_dict)

# Accessing columns in a DataFrame
names = df['Name']
ages = df['Age']

# Adding a new column to a DataFrame
df['City'] = ['New York', 'Los Angeles', 'Chicago']

# Indexing and selection
first_row = df.loc[0]    # Selecting the first row by label
first_two_rows = df.iloc[:2]  # Selecting the first two rows by integer position

print(f"Pandas Series:\n{series}")
print(f"Pandas DataFrame:\n{df}")
print(f"Names:\n{names}")
print(f"Ages:\n{ages}")
print(f"First Row:\n{first_row}")
print(f"First Two Rows:\n{first_two_rows}")


Pandas Series:
0    1
1    2
2    3
3    4
4    5
dtype: int64
Pandas DataFrame:
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
Names:
0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
Ages:
0    25
1    30
2    35
Name: Age, dtype: int64
First Row:
Name       Alice
Age           25
City    New York
Name: 0, dtype: object
First Two Rows:
    Name  Age         City
0  Alice   25     New York
1    Bob   30  Los Angeles


In [190]:
import pandas as pd

# Creating a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 30],
        'City': ['New York', 'Los Angeles', 'Chicago', 'New York']}
df = pd.DataFrame(data)

# Descriptive statistics
mean_age = df['Age'].mean()
max_age = df['Age'].max()
unique_cities = df['City'].unique()

# Filtering data
young_people = df[df['Age'] < 35]

# Grouping and aggregation
city_group = df.groupby('City')
city_mean_age = city_group['Age'].mean()

# Adding a new column based on conditions
df['Is_Young'] = df['Age'] < 35

print(f"Mean Age: {mean_age}")
print(f"Max Age: {max_age}")
print(f"Unique Cities: {unique_cities}")
print(f"Young People:\n{young_people}")
print(f"City Mean Age:\n{city_mean_age}")
print(f"DataFrame with Is_Young column:\n{df}")


Mean Age: 30.0
Max Age: 35
Unique Cities: ['New York' 'Los Angeles' 'Chicago']
Young People:
    Name  Age         City
0  Alice   25     New York
1    Bob   30  Los Angeles
3  David   30     New York
City Mean Age:
City
Chicago        35.0
Los Angeles    30.0
New York       27.5
Name: Age, dtype: float64
DataFrame with Is_Young column:
      Name  Age         City  Is_Young
0    Alice   25     New York      True
1      Bob   30  Los Angeles      True
2  Charlie   35      Chicago     False
3    David   30     New York      True
